<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYBxWNG6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYBxWNG6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYBxWNG6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYBxWNG6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYBxWNG6\App_KernelDevDebugContainer([
    'container.build_hash' => 'YBxWNG6',
    'container.build_id' => '7e99eef8',
    'container.build_time' => 1610799117,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYBxWNG6');
